project_id = "map-of-church-history"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[local_smtp]
enabled = true
port = 54325

[analytics]
enabled = true
port = 54327

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.mfa]
max_enrolled_factors = 3

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
file_size_limit = "5MiB"
